"""
Seed script: populate question_bank with pre-written TOEIC grammar questions.
Run after seed.py (topics must exist first).
20 questions per topic × 12 topics = 240 questions total.
"""

import asyncio

from sqlalchemy import delete, select

from app.core.database import AsyncSessionLocal
from app.models.grammar_topic import GrammarTopic
from app.models.question_bank import QuestionBank  # noqa: F401 — triggers model registration

# ---------------------------------------------------------------------------
# Question data: keyed by topic slug
# Format: {"question_text": str, "options": {A-D}, "correct_answer": str, "explanation": str, "difficulty": easy|medium|hard}
# ---------------------------------------------------------------------------

QUESTIONS: dict[str, list[dict]] = {
    "tenses": [
        {
            "question_text": "The annual report ______ by the accounting team every December.",
            "options": {"A": "is prepared", "B": "prepares", "C": "has prepared", "D": "was preparing"},
            "correct_answer": "A",
            "explanation": "The subject 'annual report' is passive (it doesn't prepare itself). Simple present passive 'is prepared' is correct for a recurring action.",
            "difficulty": "easy",
        },
        {
            "question_text": "By the time the manager arrived, the team ______ the presentation.",
            "options": {"A": "finished", "B": "has finished", "C": "had finished", "D": "was finishing"},
            "correct_answer": "C",
            "explanation": "Past perfect (had + V3) is used for an action completed BEFORE another past action. The manager arriving is the reference point.",
            "difficulty": "medium",
        },
        {
            "question_text": "Sales ______ steadily since we launched the new product line.",
            "options": {"A": "increase", "B": "have increased", "C": "increased", "D": "are increasing"},
            "correct_answer": "B",
            "explanation": "'Since' signals present perfect. The increase started in the past and continues to now.",
            "difficulty": "easy",
        },
        {
            "question_text": "The CEO ______ three international conferences next month.",
            "options": {"A": "attends", "B": "attended", "C": "is attending", "D": "has attended"},
            "correct_answer": "C",
            "explanation": "Present continuous is used for arranged future plans. 'Next month' confirms it's a scheduled future event.",
            "difficulty": "easy",
        },
        {
            "question_text": "The contract ______ for two years before it was finally renewed.",
            "options": {"A": "expired", "B": "had been expiring", "C": "has expired", "D": "was expired"},
            "correct_answer": "B",
            "explanation": "Past perfect continuous (had been + V-ing) shows a continuous action over a period before a past reference point.",
            "difficulty": "hard",
        },
        {
            "question_text": "She ______ at the headquarters for ten years when she was promoted.",
            "options": {"A": "works", "B": "worked", "C": "had been working", "D": "has been working"},
            "correct_answer": "C",
            "explanation": "Past perfect continuous describes an ongoing action up to a past moment. 'When she was promoted' is the past reference point.",
            "difficulty": "medium",
        },
        {
            "question_text": "The shipment ______ tomorrow morning, so please prepare the warehouse.",
            "options": {"A": "arrives", "B": "arrived", "C": "has arrived", "D": "was arriving"},
            "correct_answer": "A",
            "explanation": "Simple present is used for scheduled events on a timetable/calendar, especially with 'tomorrow'.",
            "difficulty": "medium",
        },
        {
            "question_text": "We ______ the new software by the end of this week.",
            "options": {"A": "will have installed", "B": "will install", "C": "install", "D": "are installing"},
            "correct_answer": "A",
            "explanation": "Future perfect (will have + V3) is used for an action that will be completed before a specific future time ('by the end of this week').",
            "difficulty": "hard",
        },
        {
            "question_text": "I ______ just ______ an important email from the client.",
            "options": {"A": "have / received", "B": "had / received", "C": "was / receiving", "D": "did / receive"},
            "correct_answer": "A",
            "explanation": "'Just' with present perfect (have + V3) indicates a very recent action with current relevance.",
            "difficulty": "easy",
        },
        {
            "question_text": "The policy ______ effective from January 1st every year.",
            "options": {"A": "becomes", "B": "became", "C": "has become", "D": "is becoming"},
            "correct_answer": "A",
            "explanation": "Simple present is used for recurring scheduled events or fixed rules.",
            "difficulty": "easy",
        },
        {
            "question_text": "While the director ______ the proposal, a new offer arrived.",
            "options": {"A": "reviewed", "B": "was reviewing", "C": "has reviewed", "D": "reviews"},
            "correct_answer": "B",
            "explanation": "Past continuous (was + V-ing) describes an action in progress when another action interrupted it.",
            "difficulty": "medium",
        },
        {
            "question_text": "The company ______ its headquarters to a larger building next year.",
            "options": {"A": "moves", "B": "is going to move", "C": "moved", "D": "has moved"},
            "correct_answer": "B",
            "explanation": "'Going to' is used for planned future actions. 'Next year' confirms it's future.",
            "difficulty": "easy",
        },
        {
            "question_text": "We ______ each other for years before we finally met in person.",
            "options": {"A": "knew", "B": "have known", "C": "had known", "D": "were knowing"},
            "correct_answer": "C",
            "explanation": "Past perfect shows the relationship existed before the meeting (past event). 'Know' is a stative verb and doesn't use continuous form.",
            "difficulty": "medium",
        },
        {
            "question_text": "The quarterly figures ______ not yet ______ to the board.",
            "options": {"A": "were / presented", "B": "are / presented", "C": "have / been presented", "D": "had / presented"},
            "correct_answer": "C",
            "explanation": "Present perfect passive: have + been + V3. 'Not yet' is a strong indicator of present perfect.",
            "difficulty": "medium",
        },
        {
            "question_text": "She ______ the project proposal three times before the committee accepted it.",
            "options": {"A": "revised", "B": "has revised", "C": "had revised", "D": "revises"},
            "correct_answer": "C",
            "explanation": "Past perfect (had revised) for an action completed multiple times before another past event (the committee accepting it).",
            "difficulty": "medium",
        },
        {
            "question_text": "The branch office ______ in 2018 and ______ to 50 employees since then.",
            "options": {"A": "opened / grew", "B": "opened / has grown", "C": "has opened / grew", "D": "opens / grows"},
            "correct_answer": "B",
            "explanation": "First action 'opened' is a completed past event (2018 = specific past time → simple past). 'Since then' signals present perfect for ongoing growth.",
            "difficulty": "hard",
        },
        {
            "question_text": "The technician ______ the equipment when the power outage occurred.",
            "options": {"A": "tested", "B": "is testing", "C": "was testing", "D": "had tested"},
            "correct_answer": "C",
            "explanation": "Past continuous (was testing) describes an ongoing action interrupted by a sudden event (power outage).",
            "difficulty": "easy",
        },
        {
            "question_text": "We ______ for the conference hall for two hours before we found it.",
            "options": {"A": "searched", "B": "were searching", "C": "had been searching", "D": "have searched"},
            "correct_answer": "C",
            "explanation": "Past perfect continuous shows a continuous action over a period before a past event.",
            "difficulty": "hard",
        },
        {
            "question_text": "The results of the survey ______ available online next week.",
            "options": {"A": "are made", "B": "will be made", "C": "have been made", "D": "were made"},
            "correct_answer": "B",
            "explanation": "Future passive: will be + V3. 'Next week' confirms future tense.",
            "difficulty": "easy",
        },
        {
            "question_text": "By 2030, the company ______ its carbon emissions by 50%.",
            "options": {"A": "reduces", "B": "will reduce", "C": "will have reduced", "D": "has reduced"},
            "correct_answer": "C",
            "explanation": "Future perfect (will have + V3) is used for actions completed before a specific future time ('by 2030').",
            "difficulty": "hard",
        },
    ],

    "articles": [
        {
            "question_text": "She works as ______ engineer at a multinational company.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "B",
            "explanation": "'Engineer' starts with a vowel sound /ɛ/, so 'an' is correct. Articles are used before professions when introduced.",
            "difficulty": "easy",
        },
        {
            "question_text": "Please submit ______ completed application form to the HR department.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "C",
            "explanation": "'The' is used because both speaker and listener know which specific form is referred to (the one just mentioned).",
            "difficulty": "easy",
        },
        {
            "question_text": "______ information provided in the report was accurate.",
            "options": {"A": "A", "B": "An", "C": "The", "D": "—"},
            "correct_answer": "C",
            "explanation": "'The' is used before 'information' because it's specific (the information in a specific report).",
            "difficulty": "easy",
        },
        {
            "question_text": "He has ______ MBA from Harvard Business School.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "B",
            "explanation": "'MBA' starts with the sound /ɛm/ (em), which is a vowel sound, so 'an' is correct.",
            "difficulty": "medium",
        },
        {
            "question_text": "______ management decided to restructure the entire department.",
            "options": {"A": "A", "B": "An", "C": "The", "D": "—"},
            "correct_answer": "C",
            "explanation": "'The management' refers to specific management of the company under discussion.",
            "difficulty": "easy",
        },
        {
            "question_text": "We need ______ reliable supplier for our new product line.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "A",
            "explanation": "'Reliable' starts with a consonant sound /r/, so 'a' is correct. This is an indefinite reference (any reliable supplier).",
            "difficulty": "easy",
        },
        {
            "question_text": "______ staff are encouraged to attend the training session.",
            "options": {"A": "A", "B": "An", "C": "The", "D": "—"},
            "correct_answer": "C",
            "explanation": "'The staff' refers to the specific employees of this company.",
            "difficulty": "easy",
        },
        {
            "question_text": "This is ______ most innovative product we have ever launched.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "C",
            "explanation": "Superlative adjectives always require 'the' before them.",
            "difficulty": "easy",
        },
        {
            "question_text": "She plays ______ piano at the company's annual event every year.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "C",
            "explanation": "Musical instruments require 'the': play the piano, play the guitar.",
            "difficulty": "medium",
        },
        {
            "question_text": "______ breakfast is provided for all conference attendees.",
            "options": {"A": "A", "B": "An", "C": "The", "D": "—"},
            "correct_answer": "D",
            "explanation": "Meals (breakfast, lunch, dinner) generally don't use articles when speaking generally.",
            "difficulty": "medium",
        },
        {
            "question_text": "The company headquarters is located on ______ fifth floor.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "C",
            "explanation": "Ordinal numbers (first, second, fifth) always take 'the'.",
            "difficulty": "easy",
        },
        {
            "question_text": "We received ______ unexpected call from ______ client in Tokyo.",
            "options": {"A": "an / a", "B": "a / the", "C": "an / the", "D": "the / a"},
            "correct_answer": "A",
            "explanation": "'An unexpected' (vowel sound /ʌ/); 'a client' (first mention, indefinite).",
            "difficulty": "medium",
        },
        {
            "question_text": "______ quality of the new materials exceeded our expectations.",
            "options": {"A": "A", "B": "An", "C": "The", "D": "—"},
            "correct_answer": "C",
            "explanation": "'The quality' — specific quality of specific materials discussed in context.",
            "difficulty": "easy",
        },
        {
            "question_text": "They traveled to ______ United States for the trade fair.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "C",
            "explanation": "Country names that include a common noun (States, Kingdom, Republic) take 'the': the United States, the UK.",
            "difficulty": "medium",
        },
        {
            "question_text": "It was ______ honor to receive the industry award this year.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "B",
            "explanation": "'Honor' starts with a silent 'h', so the sound is a vowel /ɒ/, requiring 'an'.",
            "difficulty": "medium",
        },
        {
            "question_text": "______ feedback from customers has been overwhelmingly positive.",
            "options": {"A": "A", "B": "An", "C": "The", "D": "—"},
            "correct_answer": "C",
            "explanation": "Specific feedback (from our customers in this campaign) → 'the'.",
            "difficulty": "easy",
        },
        {
            "question_text": "He is ______ honest employee who always meets his deadlines.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "B",
            "explanation": "'Honest' starts with a silent 'h', pronounced /ɒ/, a vowel sound → 'an'.",
            "difficulty": "medium",
        },
        {
            "question_text": "The merger created ______ unique opportunity for both companies.",
            "options": {"A": "a", "B": "an", "C": "the", "D": "—"},
            "correct_answer": "A",
            "explanation": "'Unique' starts with /juː/ (a consonant sound 'y'), so 'a unique' is correct, not 'an unique'.",
            "difficulty": "hard",
        },
        {
            "question_text": "______ research shows that remote work improves productivity.",
            "options": {"A": "A", "B": "An", "C": "The", "D": "—"},
            "correct_answer": "D",
            "explanation": "'Research' as an uncountable noun used in a general sense requires no article.",
            "difficulty": "medium",
        },
        {
            "question_text": "We submitted ______ proposal last week and received ______ response today.",
            "options": {"A": "a / the", "B": "the / a", "C": "a / a", "D": "the / the"},
            "correct_answer": "A",
            "explanation": "First mention of 'proposal' → 'a'; 'the response' refers to the response to that specific proposal → 'the'.",
            "difficulty": "medium",
        },
    ],

    "prepositions": [
        {
            "question_text": "The meeting is scheduled ______ 3 PM ______ Friday.",
            "options": {"A": "at / on", "B": "on / at", "C": "in / on", "D": "at / in"},
            "correct_answer": "A",
            "explanation": "'At' for specific times; 'on' for specific days.",
            "difficulty": "easy",
        },
        {
            "question_text": "The report must be submitted ______ the end of the month.",
            "options": {"A": "until", "B": "by", "C": "on", "D": "during"},
            "correct_answer": "B",
            "explanation": "'By' means 'no later than'. It sets a deadline. 'Until' means 'up to that time' (continuous).",
            "difficulty": "easy",
        },
        {
            "question_text": "She has been responsible ______ client relations since joining the company.",
            "options": {"A": "of", "B": "about", "C": "for", "D": "with"},
            "correct_answer": "C",
            "explanation": "'Responsible for' is a fixed collocation.",
            "difficulty": "easy",
        },
        {
            "question_text": "The new product is based ______ customer feedback from last year.",
            "options": {"A": "in", "B": "on", "C": "at", "D": "with"},
            "correct_answer": "B",
            "explanation": "'Based on' is a fixed phrase meaning 'using as a foundation'.",
            "difficulty": "easy",
        },
        {
            "question_text": "Please inform all team members ______ the schedule change.",
            "options": {"A": "about", "B": "on", "C": "for", "D": "with"},
            "correct_answer": "A",
            "explanation": "'Inform someone about/of something' are both correct; 'about' is more common in this context.",
            "difficulty": "easy",
        },
        {
            "question_text": "The new policy will take effect ______ January.",
            "options": {"A": "at", "B": "on", "C": "in", "D": "by"},
            "correct_answer": "C",
            "explanation": "'In' is used with months and years.",
            "difficulty": "easy",
        },
        {
            "question_text": "The project was delayed ______ a lack of resources.",
            "options": {"A": "because", "B": "due to", "C": "since", "D": "as"},
            "correct_answer": "B",
            "explanation": "'Due to' is a prepositional phrase followed by a noun. 'Because' is a conjunction followed by a clause.",
            "difficulty": "medium",
        },
        {
            "question_text": "We will contact you ______ 48 hours of receiving your application.",
            "options": {"A": "in", "B": "within", "C": "by", "D": "during"},
            "correct_answer": "B",
            "explanation": "'Within 48 hours' means 'no later than 48 hours'. 'In 48 hours' means after exactly 48 hours have passed.",
            "difficulty": "medium",
        },
        {
            "question_text": "The office is located ______ the corner of Main Street and 5th Avenue.",
            "options": {"A": "in", "B": "on", "C": "at", "D": "by"},
            "correct_answer": "C",
            "explanation": "'At the corner' is the standard preposition use for intersections/specific points.",
            "difficulty": "easy",
        },
        {
            "question_text": "She specializes ______ international trade law.",
            "options": {"A": "on", "B": "about", "C": "in", "D": "with"},
            "correct_answer": "C",
            "explanation": "'Specialize in' is a fixed collocation.",
            "difficulty": "easy",
        },
        {
            "question_text": "The budget was approved ______ the board ______ last Tuesday's meeting.",
            "options": {"A": "by / at", "B": "from / in", "C": "by / in", "D": "from / at"},
            "correct_answer": "A",
            "explanation": "'By the board' (agent in passive); 'at the meeting' (specific event location).",
            "difficulty": "medium",
        },
        {
            "question_text": "Sales increased ______ 15% compared ______ last year.",
            "options": {"A": "by / to", "B": "at / with", "C": "for / to", "D": "to / with"},
            "correct_answer": "A",
            "explanation": "'By' shows the amount of change (increase by 15%); 'compared to' is the fixed phrase.",
            "difficulty": "medium",
        },
        {
            "question_text": "The team worked ______ the problem for several weeks.",
            "options": {"A": "at", "B": "on", "C": "with", "D": "for"},
            "correct_answer": "B",
            "explanation": "'Work on something' means to deal with or try to solve something.",
            "difficulty": "easy",
        },
        {
            "question_text": "Please reply ______ this email ______ the close of business today.",
            "options": {"A": "to / by", "B": "for / until", "C": "with / by", "D": "to / until"},
            "correct_answer": "A",
            "explanation": "'Reply to' (verb + preposition); 'by the close of business' (deadline).",
            "difficulty": "medium",
        },
        {
            "question_text": "The company complied ______ all safety regulations.",
            "options": {"A": "to", "B": "with", "C": "by", "D": "on"},
            "correct_answer": "B",
            "explanation": "'Comply with' is a fixed collocation meaning 'follow the rules'.",
            "difficulty": "easy",
        },
        {
            "question_text": "The seminar will be held ______ the Grand Hotel ______ downtown.",
            "options": {"A": "in / at", "B": "at / in", "C": "at / on", "D": "in / on"},
            "correct_answer": "B",
            "explanation": "'At' for specific venues/locations; 'in downtown' for area/district.",
            "difficulty": "medium",
        },
        {
            "question_text": "She is very interested ______ pursuing a career ______ finance.",
            "options": {"A": "on / at", "B": "in / in", "C": "for / in", "D": "about / at"},
            "correct_answer": "B",
            "explanation": "'Interested in' (adj + prep); 'career in finance' (field of work).",
            "difficulty": "easy",
        },
        {
            "question_text": "The merger resulted ______ significant cost savings ______ both companies.",
            "options": {"A": "in / for", "B": "from / to", "C": "to / for", "D": "in / to"},
            "correct_answer": "A",
            "explanation": "'Result in' = lead to (outcome); 'for both companies' = benefiting both.",
            "difficulty": "medium",
        },
        {
            "question_text": "The proposal consists ______ three main sections.",
            "options": {"A": "with", "B": "in", "C": "of", "D": "from"},
            "correct_answer": "C",
            "explanation": "'Consist of' is a fixed phrase meaning 'be made up of'. It cannot be passive.",
            "difficulty": "easy",
        },
        {
            "question_text": "She was congratulated ______ her outstanding performance ______ the project.",
            "options": {"A": "for / on", "B": "on / for", "C": "about / in", "D": "for / in"},
            "correct_answer": "B",
            "explanation": "'Congratulate someone on something' is the standard collocation.",
            "difficulty": "medium",
        },
    ],

    "modal-verbs": [
        {
            "question_text": "All employees ______ complete the safety training before starting work.",
            "options": {"A": "can", "B": "might", "C": "must", "D": "would"},
            "correct_answer": "C",
            "explanation": "'Must' expresses a strong obligation or rule. This is a workplace requirement.",
            "difficulty": "easy",
        },
        {
            "question_text": "You ______ worry about the report — I've already submitted it.",
            "options": {"A": "must not", "B": "don't have to", "C": "cannot", "D": "should not"},
            "correct_answer": "B",
            "explanation": "'Don't have to' means there's no obligation (it's not necessary). 'Must not' means prohibition.",
            "difficulty": "medium",
        },
        {
            "question_text": "The client hasn't responded yet. She ______ be traveling.",
            "options": {"A": "must", "B": "should", "C": "will", "D": "would"},
            "correct_answer": "A",
            "explanation": "'Must' is used for logical deduction about a present situation when you're quite certain.",
            "difficulty": "medium",
        },
        {
            "question_text": "______ you please send me the updated schedule by tomorrow?",
            "options": {"A": "Will", "B": "Could", "C": "Must", "D": "Should"},
            "correct_answer": "B",
            "explanation": "'Could you' is more polite than 'Will you' for requests. 'Must' and 'Should' are not used for polite requests.",
            "difficulty": "easy",
        },
        {
            "question_text": "The package ______ arrive by now, but there's been no delivery.",
            "options": {"A": "should", "B": "must", "C": "can", "D": "will"},
            "correct_answer": "A",
            "explanation": "'Should have arrived' (implied) or 'should arrive' for expected events that haven't happened yet.",
            "difficulty": "medium",
        },
        {
            "question_text": "We ______ have informed the client earlier about the delay.",
            "options": {"A": "should", "B": "must", "C": "will", "D": "can"},
            "correct_answer": "A",
            "explanation": "'Should have + V3' expresses regret about something that wasn't done in the past.",
            "difficulty": "medium",
        },
        {
            "question_text": "Visitors ______ park in the designated areas only.",
            "options": {"A": "might", "B": "could", "C": "may", "D": "would"},
            "correct_answer": "C",
            "explanation": "'May' is used for formal permission or official rules. 'Might' is possibility, not permission.",
            "difficulty": "medium",
        },
        {
            "question_text": "The new regulation ______ affect how we handle customer data.",
            "options": {"A": "must", "B": "will", "C": "should", "D": "might"},
            "correct_answer": "D",
            "explanation": "'Might' expresses uncertain possibility (about 30-40%). The impact is not confirmed.",
            "difficulty": "easy",
        },
        {
            "question_text": "She ______ have been the one who sent the anonymous feedback — she was the only one absent.",
            "options": {"A": "can't", "B": "mustn't", "C": "shouldn't", "D": "wouldn't"},
            "correct_answer": "A",
            "explanation": "'Can't have + V3' expresses near-certain logical impossibility about a past event.",
            "difficulty": "hard",
        },
        {
            "question_text": "To qualify for the promotion, candidates ______ have at least five years of experience.",
            "options": {"A": "may", "B": "might", "C": "must", "D": "could"},
            "correct_answer": "C",
            "explanation": "'Must' states a requirement or condition that is mandatory.",
            "difficulty": "easy",
        },
        {
            "question_text": "______ I use your office for the call with the New York team?",
            "options": {"A": "Should", "B": "Must", "C": "May", "D": "Would"},
            "correct_answer": "C",
            "explanation": "'May I' is formal and polite for requesting permission.",
            "difficulty": "easy",
        },
        {
            "question_text": "The error is serious. It ______ have been caused by the software update.",
            "options": {"A": "may", "B": "should", "C": "will", "D": "must"},
            "correct_answer": "A",
            "explanation": "'May have + V3' expresses a possibility about a past event (not as certain as 'must have').",
            "difficulty": "medium",
        },
        {
            "question_text": "The system ______ automatically back up your files every night.",
            "options": {"A": "will", "B": "would", "C": "should", "D": "might"},
            "correct_answer": "A",
            "explanation": "'Will' is used for facts about how a system or process works.",
            "difficulty": "easy",
        },
        {
            "question_text": "You ______ share your login credentials with anyone.",
            "options": {"A": "don't have to", "B": "must not", "C": "may not have to", "D": "should"},
            "correct_answer": "B",
            "explanation": "'Must not' expresses strict prohibition. Sharing login credentials is forbidden, not just unnecessary.",
            "difficulty": "easy",
        },
        {
            "question_text": "The deadline has been extended, so you ______ rush to complete it today.",
            "options": {"A": "must not", "B": "can't", "C": "don't have to", "D": "shouldn't"},
            "correct_answer": "C",
            "explanation": "'Don't have to' = not necessary. The deadline extension removes the obligation.",
            "difficulty": "easy",
        },
        {
            "question_text": "If I ______ choose, I ______ hire someone with more international experience.",
            "options": {"A": "can / will", "B": "could / would", "C": "may / should", "D": "might / must"},
            "correct_answer": "B",
            "explanation": "Type 2 conditional: If + could (hypothetical ability) + would (hypothetical result).",
            "difficulty": "hard",
        },
        {
            "question_text": "She ______ be the new department head — she just started last month.",
            "options": {"A": "must", "B": "will", "C": "can't", "D": "should"},
            "correct_answer": "C",
            "explanation": "'Can't be' expresses near-certainty that something is impossible or very unlikely.",
            "difficulty": "medium",
        },
        {
            "question_text": "The conference call ______ be rescheduled due to technical issues.",
            "options": {"A": "has to", "B": "would", "C": "may", "D": "should"},
            "correct_answer": "C",
            "explanation": "'May' expresses possibility. The rescheduling is possible but not confirmed.",
            "difficulty": "easy",
        },
        {
            "question_text": "All team members ______ read the report before attending the briefing.",
            "options": {"A": "were able to", "B": "are supposed to", "C": "could", "D": "might"},
            "correct_answer": "B",
            "explanation": "'Be supposed to' indicates an expectation or obligation set by others.",
            "difficulty": "medium",
        },
        {
            "question_text": "The documents ______ be notarized before they can be submitted.",
            "options": {"A": "should", "B": "might", "C": "must", "D": "would"},
            "correct_answer": "C",
            "explanation": "'Must' for a requirement that is mandatory. Notarization is a legal necessity here.",
            "difficulty": "easy",
        },
    ],

    "conditionals": [
        {
            "question_text": "If you heat ice, it ______ into water.",
            "options": {"A": "melts", "B": "will melt", "C": "melted", "D": "would melt"},
            "correct_answer": "A",
            "explanation": "Type 0 conditional: scientific fact. Both clauses use simple present.",
            "difficulty": "easy",
        },
        {
            "question_text": "If we ______ the contract now, the project will start next month.",
            "options": {"A": "sign", "B": "signed", "C": "will sign", "D": "had signed"},
            "correct_answer": "A",
            "explanation": "Type 1 conditional: real/likely situation. 'If' clause uses simple present, main clause uses 'will'.",
            "difficulty": "easy",
        },
        {
            "question_text": "If she ______ the CEO, she would implement a four-day work week.",
            "options": {"A": "is", "B": "was", "C": "were", "D": "had been"},
            "correct_answer": "C",
            "explanation": "Type 2 conditional: unreal present situation. 'Were' is used for all subjects in formal writing.",
            "difficulty": "medium",
        },
        {
            "question_text": "If they had invested earlier, they ______ more profit by now.",
            "options": {"A": "make", "B": "would make", "C": "would have made", "D": "had made"},
            "correct_answer": "C",
            "explanation": "Type 3 conditional: impossible past situation. Main clause: would have + V3.",
            "difficulty": "medium",
        },
        {
            "question_text": "______ you submit the form on time, your application will be processed.",
            "options": {"A": "If", "B": "Unless", "C": "Provided that", "D": "In case"},
            "correct_answer": "C",
            "explanation": "'Provided that' means 'on the condition that'. 'Unless' means 'if not', which would reverse the meaning.",
            "difficulty": "medium",
        },
        {
            "question_text": "You ______ lose your badge unless you keep it in a safe place.",
            "options": {"A": "might", "B": "will", "C": "would", "D": "had"},
            "correct_answer": "A",
            "explanation": "Type 1-like conditional with 'unless' (= if not). 'Might' expresses possibility in a warning.",
            "difficulty": "medium",
        },
        {
            "question_text": "If the meeting ______ been postponed, we would have completed the audit on time.",
            "options": {"A": "hadn't", "B": "hasn't", "C": "didn't", "D": "wouldn't have"},
            "correct_answer": "A",
            "explanation": "Type 3 conditional negative: 'if + hadn't + V3' → the meeting was postponed (contrary to fact).",
            "difficulty": "hard",
        },
        {
            "question_text": "The shipment ______ arrive on time if the weather conditions improve.",
            "options": {"A": "should", "B": "can", "C": "would", "D": "might"},
            "correct_answer": "A",
            "explanation": "Type 1 conditional can use 'should' instead of 'will' to express a less certain expectation.",
            "difficulty": "medium",
        },
        {
            "question_text": "If I ______ your contact information earlier, I would have called you.",
            "options": {"A": "have", "B": "had", "C": "had had", "D": "would have"},
            "correct_answer": "C",
            "explanation": "Type 3 conditional: 'had had' = past perfect of 'have'. Past situation contrary to fact.",
            "difficulty": "hard",
        },
        {
            "question_text": "______ the client approves the design, we can proceed with production.",
            "options": {"A": "As long as", "B": "Unless", "C": "Even if", "D": "In spite of"},
            "correct_answer": "A",
            "explanation": "'As long as' = on the condition that. This is a Type 1 real conditional.",
            "difficulty": "medium",
        },
        {
            "question_text": "Save the presentation frequently ______ the computer crashes.",
            "options": {"A": "if", "B": "unless", "C": "in case", "D": "provided"},
            "correct_answer": "C",
            "explanation": "'In case' = as a precaution against the possibility of something happening.",
            "difficulty": "medium",
        },
        {
            "question_text": "Even if we ______ more time, the quality would still be the same.",
            "options": {"A": "have", "B": "had", "C": "had had", "D": "have had"},
            "correct_answer": "B",
            "explanation": "Type 2 hypothetical: 'even if' + simple past for unreal present conditions.",
            "difficulty": "medium",
        },
        {
            "question_text": "If the prototype ______ to the lab today, testing can begin immediately.",
            "options": {"A": "is sent", "B": "sends", "C": "was sent", "D": "had been sent"},
            "correct_answer": "A",
            "explanation": "Type 1 conditional with passive: 'if + is sent' (passive present) → 'can begin'.",
            "difficulty": "medium",
        },
        {
            "question_text": "She would be promoted faster ______ she networked more within the company.",
            "options": {"A": "if", "B": "unless", "C": "when", "D": "although"},
            "correct_answer": "A",
            "explanation": "Type 2 conditional structure: 'would be' in main clause → 'if + past' in condition.",
            "difficulty": "easy",
        },
        {
            "question_text": "If demand ______ to grow, we will need to expand our production capacity.",
            "options": {"A": "continues", "B": "continued", "C": "would continue", "D": "had continued"},
            "correct_answer": "A",
            "explanation": "Type 1 conditional: real future possibility. 'If' clause uses present simple.",
            "difficulty": "easy",
        },
        {
            "question_text": "Had the manager noticed the error earlier, the project ______ on schedule.",
            "options": {"A": "would be", "B": "will be", "C": "would have been", "D": "had been"},
            "correct_answer": "C",
            "explanation": "Inverted Type 3 conditional (formal): 'Had + subject + V3' = 'If + subject + had + V3'. Main clause: would have + V3.",
            "difficulty": "hard",
        },
        {
            "question_text": "We could start the campaign sooner, ______ the budget were approved this week.",
            "options": {"A": "providing", "B": "if only", "C": "in case", "D": "unless"},
            "correct_answer": "A",
            "explanation": "'Providing (that)' = on condition that. Used like 'if' for Type 2 conditions.",
            "difficulty": "hard",
        },
        {
            "question_text": "If the new regulations ______ last year, we would have restructured sooner.",
            "options": {"A": "implemented", "B": "were implemented", "C": "had been implemented", "D": "have been implemented"},
            "correct_answer": "C",
            "explanation": "Type 3 conditional passive: 'If + had been + V3' for unreal past condition.",
            "difficulty": "hard",
        },
        {
            "question_text": "The warranty ______ be void unless the product is used correctly.",
            "options": {"A": "can", "B": "will", "C": "would", "D": "must"},
            "correct_answer": "B",
            "explanation": "Type 1 conditional: real situation with 'will' in the result clause, 'unless' = if not.",
            "difficulty": "medium",
        },
        {
            "question_text": "She speaks as ______ she were the CEO of the company.",
            "options": {"A": "if", "B": "when", "C": "while", "D": "since"},
            "correct_answer": "A",
            "explanation": "'As if + past tense' expresses an unreal comparison (she is not actually the CEO).",
            "difficulty": "medium",
        },
    ],

    "passive-voice": [
        {
            "question_text": "The new policy ______ by the board of directors last week.",
            "options": {"A": "approves", "B": "was approved", "C": "has approved", "D": "is approving"},
            "correct_answer": "B",
            "explanation": "Simple past passive: was/were + V3. 'Last week' indicates past tense.",
            "difficulty": "easy",
        },
        {
            "question_text": "The quarterly report ______ to all shareholders by Friday.",
            "options": {"A": "will be sent", "B": "is sent", "C": "sends", "D": "will send"},
            "correct_answer": "A",
            "explanation": "Future passive: will be + V3. 'By Friday' is a deadline for a future action.",
            "difficulty": "easy",
        },
        {
            "question_text": "The equipment ______ currently ______ by the technical team.",
            "options": {"A": "is / inspecting", "B": "is / being inspected", "C": "has / inspected", "D": "was / inspected"},
            "correct_answer": "B",
            "explanation": "Present continuous passive: is/are + being + V3.",
            "difficulty": "medium",
        },
        {
            "question_text": "The error ______ before the product was shipped to customers.",
            "options": {"A": "corrected", "B": "has been corrected", "C": "had been corrected", "D": "was correcting"},
            "correct_answer": "C",
            "explanation": "Past perfect passive: had been + V3. The error was corrected before another past event (shipping).",
            "difficulty": "medium",
        },
        {
            "question_text": "Applicants ______ to bring two forms of identification.",
            "options": {"A": "require", "B": "are required", "C": "have required", "D": "required"},
            "correct_answer": "B",
            "explanation": "Present passive: are + V3. The rule applies to applicants generally.",
            "difficulty": "easy",
        },
        {
            "question_text": "The presentation materials ______ to all attendees after the conference.",
            "options": {"A": "will distribute", "B": "are distributing", "C": "will be distributed", "D": "distribute"},
            "correct_answer": "C",
            "explanation": "Future passive: will be + V3. The attendees receive the materials (passive action).",
            "difficulty": "easy",
        },
        {
            "question_text": "A new branch ______ in Singapore next year.",
            "options": {"A": "is opening", "B": "will be opened", "C": "opens", "D": "opened"},
            "correct_answer": "B",
            "explanation": "Future passive: will be + V3. The branch is the recipient of the action (someone opens it).",
            "difficulty": "easy",
        },
        {
            "question_text": "The issue ______ to be caused by a software bug.",
            "options": {"A": "appears", "B": "is appeared", "C": "was appeared", "D": "has appeared"},
            "correct_answer": "A",
            "explanation": "'Appear' is an intransitive verb and doesn't take passive form. 'Appears to be' is the correct structure.",
            "difficulty": "hard",
        },
        {
            "question_text": "The employees ______ of the changes before the announcement was made public.",
            "options": {"A": "informed", "B": "were informing", "C": "had been informed", "D": "have informed"},
            "correct_answer": "C",
            "explanation": "Past perfect passive: had been + V3. The informing happened before the announcement.",
            "difficulty": "medium",
        },
        {
            "question_text": "The client ______ a 20% discount on their next order.",
            "options": {"A": "was offered", "B": "offered", "C": "is offering", "D": "had offered"},
            "correct_answer": "A",
            "explanation": "Simple past passive with indirect object: the client received the offer (passive). 'Offer + person + thing' → 'person was offered thing'.",
            "difficulty": "medium",
        },
        {
            "question_text": "Instructions for the new system ______ to all employees by email.",
            "options": {"A": "are being sent", "B": "send", "C": "are sending", "D": "have sent"},
            "correct_answer": "A",
            "explanation": "Present continuous passive: is/are being + V3. The sending is in progress now.",
            "difficulty": "medium",
        },
        {
            "question_text": "The merger ______ to be completed by the end of the financial year.",
            "options": {"A": "expects", "B": "is expected", "C": "was expecting", "D": "has expected"},
            "correct_answer": "B",
            "explanation": "Passive with reporting verb: 'is expected to + V'. The subject receives the expectation.",
            "difficulty": "medium",
        },
        {
            "question_text": "The office ______ renovated while the staff worked from home.",
            "options": {"A": "was being", "B": "is being", "C": "had", "D": "has been"},
            "correct_answer": "A",
            "explanation": "Past continuous passive: was/were being + V3. Ongoing action during another past period.",
            "difficulty": "hard",
        },
        {
            "question_text": "The parking area ______ on weekdays between 8 AM and 6 PM.",
            "options": {"A": "is restricted", "B": "restricts", "C": "has restricted", "D": "restricted"},
            "correct_answer": "A",
            "explanation": "Present simple passive for ongoing rules or situations.",
            "difficulty": "easy",
        },
        {
            "question_text": "The deadline ______ extended twice due to unforeseen complications.",
            "options": {"A": "was", "B": "was being", "C": "has been", "D": "had"},
            "correct_answer": "C",
            "explanation": "Present perfect passive: has/have been + V3. The extension is relevant to the current situation.",
            "difficulty": "medium",
        },
        {
            "question_text": "All visitors ______ to sign in at the reception desk upon arrival.",
            "options": {"A": "must", "B": "are required", "C": "require", "D": "should require"},
            "correct_answer": "B",
            "explanation": "Passive with modal meaning: 'are required to + V' expresses obligation.",
            "difficulty": "easy",
        },
        {
            "question_text": "It ______ that the new model will launch in autumn.",
            "options": {"A": "is saying", "B": "says", "C": "is said", "D": "said"},
            "correct_answer": "C",
            "explanation": "Impersonal passive with reporting verb: 'It is said that...'",
            "difficulty": "medium",
        },
        {
            "question_text": "The results of the survey ______ at next month's meeting.",
            "options": {"A": "will present", "B": "are presenting", "C": "will be presented", "D": "present"},
            "correct_answer": "C",
            "explanation": "Future passive: will be + V3. The results (subject) are presented by someone else.",
            "difficulty": "easy",
        },
        {
            "question_text": "The candidate ______ well-qualified for the position.",
            "options": {"A": "is considered", "B": "considers", "C": "is considering", "D": "was considering"},
            "correct_answer": "A",
            "explanation": "Passive with adjective complement: 'is considered + adjective/noun'.",
            "difficulty": "medium",
        },
        {
            "question_text": "New safety protocols ______ in response to last month's incident.",
            "options": {"A": "have implemented", "B": "have been implemented", "C": "are implementing", "D": "implementing"},
            "correct_answer": "B",
            "explanation": "Present perfect passive: have been + V3. Protocols are relevant now (result of past action).",
            "difficulty": "medium",
        },
    ],

    "relative-clauses": [
        {
            "question_text": "The candidate ______ scored highest in the interview was offered the position.",
            "options": {"A": "who", "B": "whom", "C": "which", "D": "whose"},
            "correct_answer": "A",
            "explanation": "'Who' is used for people as the subject of the relative clause.",
            "difficulty": "easy",
        },
        {
            "question_text": "The report ______ was submitted last week contains several errors.",
            "options": {"A": "who", "B": "whom", "C": "which", "D": "whose"},
            "correct_answer": "C",
            "explanation": "'Which' is used for things as the subject or object of a relative clause.",
            "difficulty": "easy",
        },
        {
            "question_text": "The manager ______ team achieved the highest sales this quarter will receive a bonus.",
            "options": {"A": "who", "B": "whom", "C": "which", "D": "whose"},
            "correct_answer": "D",
            "explanation": "'Whose' shows possession. 'Whose team' = the manager's team.",
            "difficulty": "easy",
        },
        {
            "question_text": "The conference room ______ the meeting was held is on the third floor.",
            "options": {"A": "which", "B": "that", "C": "where", "D": "when"},
            "correct_answer": "C",
            "explanation": "'Where' refers to a place and acts as an adverb (= in which the meeting was held).",
            "difficulty": "medium",
        },
        {
            "question_text": "Ms. Johnson, ______ was hired three months ago, has already been promoted.",
            "options": {"A": "that", "B": "which", "C": "who", "D": "whom"},
            "correct_answer": "C",
            "explanation": "Non-defining clause (has commas) → cannot use 'that'. 'Who' for a person.",
            "difficulty": "medium",
        },
        {
            "question_text": "This is the proposal ______ we discussed in yesterday's meeting.",
            "options": {"A": "who", "B": "whose", "C": "where", "D": "that"},
            "correct_answer": "D",
            "explanation": "'That' or 'which' for things as object of relative clause. Either works, but 'that' is also acceptable here.",
            "difficulty": "easy",
        },
        {
            "question_text": "The new software, ______ was developed in-house, has reduced processing time by 40%.",
            "options": {"A": "that", "B": "which", "C": "who", "D": "when"},
            "correct_answer": "B",
            "explanation": "Non-defining clause (commas present) → must use 'which', not 'that'.",
            "difficulty": "medium",
        },
        {
            "question_text": "The employees ______ contracts expire this year will be given renewal offers.",
            "options": {"A": "who", "B": "whom", "C": "whose", "D": "which"},
            "correct_answer": "C",
            "explanation": "'Whose' for possessive: 'their contracts' → 'whose contracts'.",
            "difficulty": "medium",
        },
        {
            "question_text": "The day ______ we finalize the merger will be a historic moment for the company.",
            "options": {"A": "which", "B": "when", "C": "where", "D": "that"},
            "correct_answer": "B",
            "explanation": "'When' refers to time (= on which).",
            "difficulty": "medium",
        },
        {
            "question_text": "That is the manager to ______ I reported the issue.",
            "options": {"A": "who", "B": "whom", "C": "which", "D": "that"},
            "correct_answer": "B",
            "explanation": "After a preposition ('to'), use 'whom' (not 'who'). 'That' cannot follow a preposition.",
            "difficulty": "hard",
        },
        {
            "question_text": "The office building ______ the new startup company moved is very modern.",
            "options": {"A": "which", "B": "that", "C": "into which", "D": "where"},
            "correct_answer": "D",
            "explanation": "'Where' = the place in which. Simplest and most natural option for location.",
            "difficulty": "medium",
        },
        {
            "question_text": "The candidates ______ applications were rejected received a notification by email.",
            "options": {"A": "who", "B": "whom", "C": "which", "D": "whose"},
            "correct_answer": "D",
            "explanation": "'Whose applications' — possessive relationship between candidates and applications.",
            "difficulty": "medium",
        },
        {
            "question_text": "Everything ______ was discussed in the meeting will be summarized in the minutes.",
            "options": {"A": "which", "B": "who", "C": "that", "D": "whom"},
            "correct_answer": "C",
            "explanation": "After 'everything', 'all', 'only', use 'that' (not 'which').",
            "difficulty": "hard",
        },
        {
            "question_text": "The survey, ______ results were released yesterday, shows strong consumer confidence.",
            "options": {"A": "that", "B": "which", "C": "whose", "D": "whom"},
            "correct_answer": "C",
            "explanation": "Non-defining clause about a thing with possessive → 'whose results'.",
            "difficulty": "hard",
        },
        {
            "question_text": "The person ______ the HR team recommended for the position has accepted the offer.",
            "options": {"A": "who", "B": "whom", "C": "which", "D": "that"},
            "correct_answer": "B",
            "explanation": "'Whom' when the relative pronoun is the object of the verb in the clause (team recommended him/her → whom).",
            "difficulty": "hard",
        },
        {
            "question_text": "The reason ______ she resigned was never officially announced.",
            "options": {"A": "which", "B": "where", "C": "why", "D": "when"},
            "correct_answer": "C",
            "explanation": "'Why' is used after 'reason' in relative clauses (= for which).",
            "difficulty": "medium",
        },
        {
            "question_text": "The company's latest product, ______ I have already reviewed, is impressive.",
            "options": {"A": "that", "B": "which", "C": "who", "D": "whom"},
            "correct_answer": "B",
            "explanation": "Non-defining clause (commas) for a thing → 'which'.",
            "difficulty": "easy",
        },
        {
            "question_text": "Employees ______ perform well consistently are first considered for promotion.",
            "options": {"A": "whom", "B": "which", "C": "who", "D": "whose"},
            "correct_answer": "C",
            "explanation": "'Who' for people as the subject of the relative clause.",
            "difficulty": "easy",
        },
        {
            "question_text": "The training program ______ offered by the company is available to all staff.",
            "options": {"A": "who", "B": "—", "C": "whom", "D": "whose"},
            "correct_answer": "B",
            "explanation": "This is a reduced relative clause (which is offered → offered). No relative pronoun needed when reducing passive relative clauses to past participle phrases.",
            "difficulty": "hard",
        },
        {
            "question_text": "The first candidate ______ arrives will be interviewed immediately.",
            "options": {"A": "whom", "B": "whose", "C": "which", "D": "who"},
            "correct_answer": "D",
            "explanation": "'Who' for people as the subject. 'First' doesn't change the rule, though 'that' would also be acceptable.",
            "difficulty": "easy",
        },
    ],

    "subject-verb-agreement": [
        {
            "question_text": "The committee ______ its decision after a long debate.",
            "options": {"A": "announce", "B": "announces", "C": "have announced", "D": "are announcing"},
            "correct_answer": "B",
            "explanation": "Collective nouns like 'committee' take singular verbs in American English (TOEIC standard).",
            "difficulty": "easy",
        },
        {
            "question_text": "Neither the director nor the employees ______ aware of the change.",
            "options": {"A": "was", "B": "were", "C": "is", "D": "has been"},
            "correct_answer": "B",
            "explanation": "With neither...nor, the verb agrees with the closer subject ('employees' is plural → were).",
            "difficulty": "medium",
        },
        {
            "question_text": "A number of applications ______ received in the first hour.",
            "options": {"A": "was", "B": "is", "C": "were", "D": "has been"},
            "correct_answer": "C",
            "explanation": "'A number of + plural noun' takes a plural verb.",
            "difficulty": "medium",
        },
        {
            "question_text": "The number of qualified candidates ______ decreased significantly.",
            "options": {"A": "have", "B": "has", "C": "are", "D": "were"},
            "correct_answer": "B",
            "explanation": "'The number of + plural noun' takes a singular verb.",
            "difficulty": "medium",
        },
        {
            "question_text": "Everyone in the three departments ______ required to attend the briefing.",
            "options": {"A": "are", "B": "were", "C": "is", "D": "have been"},
            "correct_answer": "C",
            "explanation": "'Everyone' is an indefinite pronoun and always takes a singular verb.",
            "difficulty": "easy",
        },
        {
            "question_text": "The staff ______ been notified of the new dress code policy.",
            "options": {"A": "have", "B": "has", "C": "are", "D": "were"},
            "correct_answer": "B",
            "explanation": "'Staff' as a collective noun takes a singular verb in formal/TOEIC American English.",
            "difficulty": "medium",
        },
        {
            "question_text": "Economics ______ a mandatory subject for all business students.",
            "options": {"A": "are", "B": "is", "C": "were", "D": "have been"},
            "correct_answer": "B",
            "explanation": "Academic subjects ending in -ics (economics, mathematics, physics) take singular verbs.",
            "difficulty": "medium",
        },
        {
            "question_text": "Either the project manager or the team leaders ______ to present the findings.",
            "options": {"A": "is", "B": "are", "C": "was", "D": "has"},
            "correct_answer": "B",
            "explanation": "With either...or, the verb agrees with the subject closest to it ('team leaders' is plural → are).",
            "difficulty": "medium",
        },
        {
            "question_text": "The CEO, together with all senior managers, ______ the restructuring plan.",
            "options": {"A": "support", "B": "are supporting", "C": "supports", "D": "have supported"},
            "correct_answer": "C",
            "explanation": "'Together with' is a non-essential phrase. The subject is 'the CEO' (singular → supports).",
            "difficulty": "hard",
        },
        {
            "question_text": "Three years ______ a long time to wait for a promotion.",
            "options": {"A": "are", "B": "were", "C": "is", "D": "have been"},
            "correct_answer": "C",
            "explanation": "When a period of time is seen as a single unit/amount, use a singular verb.",
            "difficulty": "medium",
        },
        {
            "question_text": "The news about the layoffs ______ staff morale significantly.",
            "options": {"A": "affect", "B": "affects", "C": "have affected", "D": "are affecting"},
            "correct_answer": "B",
            "explanation": "'News' is uncountable and always takes a singular verb.",
            "difficulty": "easy",
        },
        {
            "question_text": "Each of the proposals ______ its own merits and drawbacks.",
            "options": {"A": "have", "B": "has", "C": "are", "D": "were"},
            "correct_answer": "B",
            "explanation": "'Each of + plural noun' takes a singular verb.",
            "difficulty": "medium",
        },
        {
            "question_text": "The marketing team, as well as the design team, ______ the new brand identity.",
            "options": {"A": "have approved", "B": "approve", "C": "has approved", "D": "are approving"},
            "correct_answer": "C",
            "explanation": "'As well as' creates an additional phrase, not a compound subject. The main subject is 'team' (singular).",
            "difficulty": "hard",
        },
        {
            "question_text": "Neither of the two options ______ acceptable to the board.",
            "options": {"A": "are", "B": "were", "C": "is", "D": "have been"},
            "correct_answer": "C",
            "explanation": "'Neither of + plural noun' takes a singular verb.",
            "difficulty": "medium",
        },
        {
            "question_text": "The majority of employees ______ satisfied with the new benefits package.",
            "options": {"A": "is", "B": "are", "C": "was", "D": "has been"},
            "correct_answer": "B",
            "explanation": "'The majority of + plural noun' takes a plural verb.",
            "difficulty": "medium",
        },
        {
            "question_text": "Not only the price but also the quality ______ improved under new management.",
            "options": {"A": "have", "B": "has", "C": "are", "D": "were"},
            "correct_answer": "B",
            "explanation": "With 'not only...but also', the verb agrees with the subject closest to it ('quality' is singular).",
            "difficulty": "hard",
        },
        {
            "question_text": "Twenty percent of the budget ______ allocated to marketing activities.",
            "options": {"A": "are", "B": "were", "C": "is", "D": "have been"},
            "correct_answer": "C",
            "explanation": "Fractions and percentages take a verb based on the noun following 'of'. 'Budget' is uncountable/singular.",
            "difficulty": "hard",
        },
        {
            "question_text": "The board of directors ______ meeting to discuss the acquisition.",
            "options": {"A": "are", "B": "is", "C": "were", "D": "have been"},
            "correct_answer": "B",
            "explanation": "'The board of directors' = collective noun, treated as singular in TOEIC.",
            "difficulty": "medium",
        },
        {
            "question_text": "There ______ several important issues that need to be addressed immediately.",
            "options": {"A": "is", "B": "are", "C": "was", "D": "has been"},
            "correct_answer": "B",
            "explanation": "In 'there is/are' constructions, the verb agrees with the subject that follows. 'Issues' is plural → are.",
            "difficulty": "easy",
        },
        {
            "question_text": "Every document and file ______ properly labeled and archived.",
            "options": {"A": "were", "B": "are", "C": "has been", "D": "have been"},
            "correct_answer": "C",
            "explanation": "'Every + N1 and N2' takes a singular verb — 'every' makes each item singular.",
            "difficulty": "hard",
        },
    ],

    "gerunds-infinitives": [
        {
            "question_text": "The manager suggested ______ the meeting to next week.",
            "options": {"A": "to postpone", "B": "postponing", "C": "postponed", "D": "postpone"},
            "correct_answer": "B",
            "explanation": "'Suggest' is followed by a gerund (V-ing), not an infinitive.",
            "difficulty": "easy",
        },
        {
            "question_text": "She managed ______ the project ahead of schedule.",
            "options": {"A": "completing", "B": "to complete", "C": "completed", "D": "complete"},
            "correct_answer": "B",
            "explanation": "'Manage' is followed by the infinitive (to + V).",
            "difficulty": "easy",
        },
        {
            "question_text": "We look forward to ______ from you soon.",
            "options": {"A": "hear", "B": "heard", "C": "hearing", "D": "have heard"},
            "correct_answer": "C",
            "explanation": "'Look forward to' — 'to' is a preposition here, so it must be followed by V-ing.",
            "difficulty": "medium",
        },
        {
            "question_text": "The company decided ______ its operations to three new countries.",
            "options": {"A": "expanding", "B": "to expand", "C": "expand", "D": "expanded"},
            "correct_answer": "B",
            "explanation": "'Decide' is followed by an infinitive (to + V).",
            "difficulty": "easy",
        },
        {
            "question_text": "He is responsible for ______ the safety standards.",
            "options": {"A": "maintain", "B": "maintained", "C": "maintains", "D": "maintaining"},
            "correct_answer": "D",
            "explanation": "After a preposition ('for'), use a gerund (V-ing).",
            "difficulty": "easy",
        },
        {
            "question_text": "Please avoid ______ technical terms that clients may not understand.",
            "options": {"A": "to use", "B": "use", "C": "using", "D": "used"},
            "correct_answer": "C",
            "explanation": "'Avoid' is followed by a gerund (V-ing), not an infinitive.",
            "difficulty": "easy",
        },
        {
            "question_text": "The consultant recommended ______ a detailed market analysis before investing.",
            "options": {"A": "conduct", "B": "conducted", "C": "to conduct", "D": "conducting"},
            "correct_answer": "D",
            "explanation": "'Recommend' takes a gerund: recommend + V-ing.",
            "difficulty": "easy",
        },
        {
            "question_text": "She stopped ______ the presentation to answer a question from the audience.",
            "options": {"A": "giving", "B": "to give", "C": "give", "D": "given"},
            "correct_answer": "B",
            "explanation": "'Stop + infinitive' = stop in order to do something. 'Stop + gerund' = stop the activity itself.",
            "difficulty": "medium",
        },
        {
            "question_text": "We are committed ______ excellent customer service.",
            "options": {"A": "to deliver", "B": "to delivering", "C": "delivering", "D": "deliver"},
            "correct_answer": "B",
            "explanation": "'Committed to' — 'to' is a preposition here, so use V-ing.",
            "difficulty": "medium",
        },
        {
            "question_text": "The new regulations require all suppliers ______ regular audits.",
            "options": {"A": "conducting", "B": "to conduct", "C": "conduct", "D": "conducted"},
            "correct_answer": "B",
            "explanation": "'Require + object + to + V' is the correct structure.",
            "difficulty": "medium",
        },
        {
            "question_text": "I remember ______ this client at a trade fair two years ago.",
            "options": {"A": "to meet", "B": "meet", "C": "met", "D": "meeting"},
            "correct_answer": "D",
            "explanation": "'Remember + gerund' = recall a past action. 'Remember + infinitive' = remember to do something in the future.",
            "difficulty": "medium",
        },
        {
            "question_text": "The HR team helped the new employees ______ settle into their roles.",
            "options": {"A": "to", "B": "—", "C": "for", "D": "by"},
            "correct_answer": "B",
            "explanation": "'Help + object + V (bare infinitive)' — 'to' is optional but the base form ('settle') is also correct without 'to'.",
            "difficulty": "hard",
        },
        {
            "question_text": "The director agreed ______ the project timeline by two weeks.",
            "options": {"A": "extending", "B": "to extend", "C": "extend", "D": "extended"},
            "correct_answer": "B",
            "explanation": "'Agree' is followed by an infinitive (to + V).",
            "difficulty": "easy",
        },
        {
            "question_text": "The company is used to ______ in highly competitive markets.",
            "options": {"A": "operate", "B": "operating", "C": "be operating", "D": "have operated"},
            "correct_answer": "B",
            "explanation": "'Be used to + V-ing' means 'accustomed to'. 'To' here is a preposition.",
            "difficulty": "medium",
        },
        {
            "question_text": "There is no point ______ the meeting if half the team is absent.",
            "options": {"A": "to hold", "B": "in holding", "C": "hold", "D": "held"},
            "correct_answer": "B",
            "explanation": "'There is no point in + V-ing' is a fixed expression.",
            "difficulty": "hard",
        },
        {
            "question_text": "She regrets ______ the offer from the competing firm last year.",
            "options": {"A": "to reject", "B": "rejecting", "C": "rejected", "D": "reject"},
            "correct_answer": "B",
            "explanation": "'Regret + gerund' = feel sorry about a past action (she rejected the offer and now regrets it).",
            "difficulty": "medium",
        },
        {
            "question_text": "The manager had the report ______ by an external consultant.",
            "options": {"A": "reviewing", "B": "reviewed", "C": "to review", "D": "review"},
            "correct_answer": "B",
            "explanation": "'Have + object + V3 (past participle)' = causative structure meaning someone else did it.",
            "difficulty": "hard",
        },
        {
            "question_text": "Would you mind ______ the volume during the presentation?",
            "options": {"A": "to lower", "B": "lower", "C": "lowering", "D": "lowered"},
            "correct_answer": "C",
            "explanation": "'Would you mind + V-ing?' is a polite request structure that requires a gerund.",
            "difficulty": "easy",
        },
        {
            "question_text": "We expect ______ a decision from the board by the end of the week.",
            "options": {"A": "receiving", "B": "to receive", "C": "received", "D": "receive"},
            "correct_answer": "B",
            "explanation": "'Expect' is followed by an infinitive (to + V).",
            "difficulty": "easy",
        },
        {
            "question_text": "______ in a global market requires cross-cultural communication skills.",
            "options": {"A": "Compete", "B": "Competing", "C": "To competing", "D": "Competed"},
            "correct_answer": "B",
            "explanation": "A gerund (V-ing) can function as the subject of a sentence.",
            "difficulty": "easy",
        },
    ],

    "comparatives-superlatives": [
        {
            "question_text": "This quarter's profit margin is ______ than the previous year's.",
            "options": {"A": "more high", "B": "highest", "C": "higher", "D": "more higher"},
            "correct_answer": "C",
            "explanation": "'High' is a one-syllable adjective. Comparative: add -er → 'higher'.",
            "difficulty": "easy",
        },
        {
            "question_text": "This is ______ innovative product the company has ever developed.",
            "options": {"A": "a more", "B": "the most", "C": "more", "D": "most"},
            "correct_answer": "B",
            "explanation": "Superlative of a multi-syllable adjective: 'the most + adjective'.",
            "difficulty": "easy",
        },
        {
            "question_text": "The new system processes data ______ times faster than the old one.",
            "options": {"A": "three", "B": "three more", "C": "triple", "D": "more three"},
            "correct_answer": "A",
            "explanation": "'Three times faster' = multiplier + comparative form. 'Three times as fast as' is also correct.",
            "difficulty": "medium",
        },
        {
            "question_text": "She has ______ experience in project management than any other candidate.",
            "options": {"A": "more", "B": "most", "C": "much", "D": "the most"},
            "correct_answer": "A",
            "explanation": "'More experience than' is a comparative structure with 'than' following.",
            "difficulty": "easy",
        },
        {
            "question_text": "The results are not ______ good ______ we had expected.",
            "options": {"A": "so / as", "B": "as / than", "C": "so / than", "D": "as / as"},
            "correct_answer": "D",
            "explanation": "'Not as...as' is the structure for negative equality: not as good as expected.",
            "difficulty": "easy",
        },
        {
            "question_text": "______ budget we allocate to marketing, ______ results we tend to see.",
            "options": {"A": "The more / the better", "B": "More / better", "C": "The most / the best", "D": "A more / a better"},
            "correct_answer": "A",
            "explanation": "'The + comparative, the + comparative' expresses proportional relationships.",
            "difficulty": "medium",
        },
        {
            "question_text": "The new model is ______ to the older version in terms of features.",
            "options": {"A": "superior", "B": "more superior", "C": "superiorest", "D": "superiorer"},
            "correct_answer": "A",
            "explanation": "'Superior' is already comparative in meaning. It is followed by 'to', not 'than'. No 'more' is needed.",
            "difficulty": "medium",
        },
        {
            "question_text": "Among all the candidates, she was ______ qualified for the role.",
            "options": {"A": "most", "B": "the most", "C": "more", "D": "a most"},
            "correct_answer": "B",
            "explanation": "Superlative form with 'the most' when comparing within a group ('among all').",
            "difficulty": "easy",
        },
        {
            "question_text": "Our customer satisfaction scores are becoming ______ every quarter.",
            "options": {"A": "more good", "B": "the best", "C": "better and better", "D": "more and more good"},
            "correct_answer": "C",
            "explanation": "'Comparative + and + comparative' expresses a continuing change. 'Better and better' is the correct form.",
            "difficulty": "medium",
        },
        {
            "question_text": "This is the ______ decision the board has made in decades.",
            "options": {"A": "more costly", "B": "most costly", "C": "costlier", "D": "as costly"},
            "correct_answer": "B",
            "explanation": "Superlative: 'the most costly'. 'Costly' (2+ syllables) uses 'most', not -est.",
            "difficulty": "easy",
        },
        {
            "question_text": "The new branch is twice ______ the original headquarters.",
            "options": {"A": "as large than", "B": "as large as", "C": "larger than", "D": "the largest of"},
            "correct_answer": "B",
            "explanation": "Multiplier + 'as + adjective + as': 'twice as large as'.",
            "difficulty": "medium",
        },
        {
            "question_text": "This position requires someone ______ dedicated ______ the current holder.",
            "options": {"A": "as / as", "B": "more / than", "C": "as / than", "D": "the most / as"},
            "correct_answer": "A",
            "explanation": "'As dedicated as' is the equality comparison structure.",
            "difficulty": "easy",
        },
        {
            "question_text": "The performance of junior staff was ______ than that of senior managers.",
            "options": {"A": "more impressive", "B": "most impressive", "C": "impressiver", "D": "as impressive"},
            "correct_answer": "A",
            "explanation": "'More + long adjective + than' for comparative.",
            "difficulty": "easy",
        },
        {
            "question_text": "This solution is far ______ practical than the one proposed last month.",
            "options": {"A": "most", "B": "more", "C": "much more", "D": "the more"},
            "correct_answer": "C",
            "explanation": "'Much more' intensifies the comparative. 'Far more' also works. 'More' alone is also grammatically correct but 'much more' is the strongest reinforcement.",
            "difficulty": "medium",
        },
        {
            "question_text": "Our new electric vehicles are ______ efficient than gasoline-powered ones.",
            "options": {"A": "more", "B": "most", "C": "the most", "D": "much"},
            "correct_answer": "A",
            "explanation": "'More efficient than' is the standard comparative structure for multi-syllable adjectives.",
            "difficulty": "easy",
        },
        {
            "question_text": "The service at this hotel is ______ I have ever experienced.",
            "options": {"A": "the best that", "B": "better than", "C": "as good as", "D": "the better"},
            "correct_answer": "A",
            "explanation": "'The best that + subject + have ever + V3' is a superlative with relative clause structure.",
            "difficulty": "medium",
        },
        {
            "question_text": "The senior consultant is ______ the junior staff in terms of experience.",
            "options": {"A": "more senior than", "B": "senior to", "C": "the most senior than", "D": "senior than"},
            "correct_answer": "B",
            "explanation": "'Senior to' — like 'superior to', 'senior' is used with 'to', not 'than'.",
            "difficulty": "hard",
        },
        {
            "question_text": "The larger the team, ______ complex the communication becomes.",
            "options": {"A": "more", "B": "the more", "C": "most", "D": "the most"},
            "correct_answer": "B",
            "explanation": "'The + comparative... the + comparative' structure requires 'the more' in the second clause.",
            "difficulty": "medium",
        },
        {
            "question_text": "Of the two proposals, the second one is clearly ______.",
            "options": {"A": "most detailed", "B": "the most detailed", "C": "more detailed", "D": "the more detailed"},
            "correct_answer": "D",
            "explanation": "When comparing exactly two things, use 'the + comparative' (the more detailed of the two).",
            "difficulty": "hard",
        },
        {
            "question_text": "The product's performance is ______ that of its competitors.",
            "options": {"A": "far superior to", "B": "far superior than", "C": "much more superior to", "D": "the most superior than"},
            "correct_answer": "A",
            "explanation": "'Superior to' (not 'than'). 'Far' intensifies the comparison. 'More superior' is redundant.",
            "difficulty": "medium",
        },
    ],

    "conjunctions-connectors": [
        {
            "question_text": "The meeting was productive; ______, no final decision was made.",
            "options": {"A": "therefore", "B": "however", "C": "moreover", "D": "furthermore"},
            "correct_answer": "B",
            "explanation": "'However' introduces a contrasting idea. Productive but no decision = contrast.",
            "difficulty": "easy",
        },
        {
            "question_text": "______ the high cost, the board approved the renovation project.",
            "options": {"A": "Although", "B": "Despite", "C": "Even though", "D": "However"},
            "correct_answer": "B",
            "explanation": "'Despite' is a preposition followed by a noun phrase ('the high cost'). 'Although' and 'Even though' require a clause.",
            "difficulty": "medium",
        },
        {
            "question_text": "We reviewed the budget ______ requested additional funding from headquarters.",
            "options": {"A": "and", "B": "but", "C": "so", "D": "nor"},
            "correct_answer": "A",
            "explanation": "'And' joins two related actions sequentially. Both reviewing and requesting are positive/neutral actions.",
            "difficulty": "easy",
        },
        {
            "question_text": "Sales have declined ______ the company launched an aggressive marketing campaign.",
            "options": {"A": "although", "B": "because", "C": "therefore", "D": "besides"},
            "correct_answer": "A",
            "explanation": "'Although' introduces a contrasting clause (despite the campaign, sales still declined).",
            "difficulty": "medium",
        },
        {
            "question_text": "The project was delayed; ______, costs increased significantly.",
            "options": {"A": "however", "B": "moreover", "C": "consequently", "D": "otherwise"},
            "correct_answer": "C",
            "explanation": "'Consequently' = as a result. The delay caused the cost increase (cause and effect).",
            "difficulty": "easy",
        },
        {
            "question_text": "You must complete the online form ______ visiting the office in person.",
            "options": {"A": "instead of", "B": "in addition to", "C": "in spite of", "D": "because of"},
            "correct_answer": "A",
            "explanation": "'Instead of' + V-ing indicates a replacement/alternative action.",
            "difficulty": "medium",
        },
        {
            "question_text": "The company offers both competitive salaries ______ excellent benefits.",
            "options": {"A": "or", "B": "but", "C": "and", "D": "nor"},
            "correct_answer": "C",
            "explanation": "'Both...and' is a correlative conjunction for listing two equal elements.",
            "difficulty": "easy",
        },
        {
            "question_text": "She accepted the position ______ the salary was lower than expected.",
            "options": {"A": "because", "B": "so that", "C": "even though", "D": "as a result"},
            "correct_answer": "C",
            "explanation": "'Even though' introduces a contrasting clause (she accepted despite lower salary).",
            "difficulty": "easy",
        },
        {
            "question_text": "Submit the form online ______ email it to the HR department.",
            "options": {"A": "or", "B": "and", "C": "but", "D": "so"},
            "correct_answer": "A",
            "explanation": "'Or' presents two alternative options.",
            "difficulty": "easy",
        },
        {
            "question_text": "The training was designed ______ all employees could benefit from it.",
            "options": {"A": "so that", "B": "because", "C": "although", "D": "even if"},
            "correct_answer": "A",
            "explanation": "'So that' expresses purpose — the reason the training was designed.",
            "difficulty": "medium",
        },
        {
            "question_text": "______ his extensive experience, he was passed over for the promotion.",
            "options": {"A": "Because of", "B": "Despite", "C": "Since", "D": "As a result of"},
            "correct_answer": "B",
            "explanation": "'Despite' + noun phrase = even though he had experience. Contrast between experience and being passed over.",
            "difficulty": "medium",
        },
        {
            "question_text": "Not only ______ the deadline, but the team also exceeded quality expectations.",
            "options": {"A": "they met", "B": "did they meet", "C": "they have met", "D": "they meeting"},
            "correct_answer": "B",
            "explanation": "After 'not only' at the start of a clause, inversion occurs: 'Not only did + subject + V'.",
            "difficulty": "hard",
        },
        {
            "question_text": "The report must be submitted by Friday; ______, the project funding may be frozen.",
            "options": {"A": "moreover", "B": "however", "C": "otherwise", "D": "therefore"},
            "correct_answer": "C",
            "explanation": "'Otherwise' = or else, if not. If it's not submitted, funding may be frozen.",
            "difficulty": "medium",
        },
        {
            "question_text": "We reduced marketing costs ______ maintaining the quality of our campaigns.",
            "options": {"A": "while", "B": "so that", "C": "although", "D": "because"},
            "correct_answer": "A",
            "explanation": "'While' + V-ing shows two simultaneous actions or a contrast.",
            "difficulty": "medium",
        },
        {
            "question_text": "The company has grown significantly; ______, it has maintained its core values.",
            "options": {"A": "consequently", "B": "furthermore", "C": "nevertheless", "D": "therefore"},
            "correct_answer": "C",
            "explanation": "'Nevertheless' = despite this / in spite of this. Growth happened, but values were still maintained (concession).",
            "difficulty": "medium",
        },
        {
            "question_text": "He is a skilled developer ______ an experienced project manager.",
            "options": {"A": "and also", "B": "as well as", "C": "but also", "D": "in addition"},
            "correct_answer": "B",
            "explanation": "'As well as' connects two noun phrases showing both qualities. 'And also' would need 'not only' before.",
            "difficulty": "medium",
        },
        {
            "question_text": "______ the candidate lacks experience, her skills are impressive.",
            "options": {"A": "Because", "B": "So", "C": "While", "D": "Therefore"},
            "correct_answer": "C",
            "explanation": "'While' here introduces a concession (= although). It contrasts the lack of experience with impressive skills.",
            "difficulty": "medium",
        },
        {
            "question_text": "The conference was canceled ______ to low registration numbers.",
            "options": {"A": "because", "B": "due", "C": "as", "D": "since"},
            "correct_answer": "B",
            "explanation": "'Due to' (preposition phrase) is followed by a noun phrase. Only 'due' fits before 'to low registration numbers'.",
            "difficulty": "easy",
        },
        {
            "question_text": "Neither the CEO ______ the CFO was available for comment.",
            "options": {"A": "and", "B": "nor", "C": "or", "D": "but"},
            "correct_answer": "B",
            "explanation": "'Neither...nor' is a correlative conjunction for two negative alternatives.",
            "difficulty": "easy",
        },
        {
            "question_text": "She stayed late ______ she could finish the proposal before the deadline.",
            "options": {"A": "so that", "B": "even though", "C": "unless", "D": "whereas"},
            "correct_answer": "A",
            "explanation": "'So that' indicates purpose — she stayed late for the purpose of finishing.",
            "difficulty": "easy",
        },
    ],

    "word-forms": [
        {
            "question_text": "The company's new strategy has shown remarkable ______ in reducing costs.",
            "options": {"A": "effective", "B": "effectively", "C": "effectiveness", "D": "effect"},
            "correct_answer": "C",
            "explanation": "After 'remarkable' (adjective modifying a noun), a noun is needed. 'Effectiveness' is the noun form.",
            "difficulty": "easy",
        },
        {
            "question_text": "She speaks very ______ in front of large audiences.",
            "options": {"A": "confident", "B": "confidence", "C": "confidently", "D": "confide"},
            "correct_answer": "C",
            "explanation": "Adverb needed to modify the verb 'speaks'. 'Confidently' = adjective 'confident' + -ly.",
            "difficulty": "easy",
        },
        {
            "question_text": "The board requires a thorough ______ of all financial records.",
            "options": {"A": "examine", "B": "examining", "C": "examination", "D": "examined"},
            "correct_answer": "C",
            "explanation": "After 'a thorough' (article + adjective), a noun is required. 'Examination' is the noun form of 'examine'.",
            "difficulty": "easy",
        },
        {
            "question_text": "His ______ of the market trends helped the company avoid a major loss.",
            "options": {"A": "analyze", "B": "analytical", "C": "analysis", "D": "analytically"},
            "correct_answer": "C",
            "explanation": "After 'his' (possessive), a noun is needed. 'Analysis' is the noun form of 'analyze'.",
            "difficulty": "easy",
        },
        {
            "question_text": "The new regulations are designed to ______ the quality of exported goods.",
            "options": {"A": "improvement", "B": "improving", "C": "improve", "D": "improved"},
            "correct_answer": "C",
            "explanation": "After 'to' (infinitive marker), a base verb is required. 'Improve' is the base form.",
            "difficulty": "easy",
        },
        {
            "question_text": "The CEO gave a very ______ speech at the annual shareholders' meeting.",
            "options": {"A": "inspire", "B": "inspiration", "C": "inspired", "D": "inspiring"},
            "correct_answer": "D",
            "explanation": "'Inspiring' (present participle used as adjective) describes the speech as causing inspiration. 'Inspired' would describe the audience.",
            "difficulty": "medium",
        },
        {
            "question_text": "There has been a significant ______ in customer complaints since the update.",
            "options": {"A": "reduce", "B": "reduction", "C": "reducing", "D": "reduced"},
            "correct_answer": "B",
            "explanation": "After 'a significant' (article + adjective), a noun is needed. 'Reduction' is the noun form.",
            "difficulty": "easy",
        },
        {
            "question_text": "The new hire proved to be extremely ______ in his first month.",
            "options": {"A": "produce", "B": "productivity", "C": "productively", "D": "productive"},
            "correct_answer": "D",
            "explanation": "After 'be' (linking verb), an adjective is used. 'Productive' describes the new hire.",
            "difficulty": "easy",
        },
        {
            "question_text": "All staff are ______ encouraged to participate in the wellness program.",
            "options": {"A": "strong", "B": "strength", "C": "strongly", "D": "strengthen"},
            "correct_answer": "C",
            "explanation": "An adverb is needed to modify the past participle 'encouraged'. 'Strongly' = strong + -ly.",
            "difficulty": "easy",
        },
        {
            "question_text": "The team needs someone with ______ knowledge of data analysis tools.",
            "options": {"A": "extend", "B": "extensively", "C": "extension", "D": "extensive"},
            "correct_answer": "D",
            "explanation": "An adjective is needed before the noun 'knowledge'. 'Extensive' = thorough, wide-ranging.",
            "difficulty": "easy",
        },
        {
            "question_text": "The ______ of the new product was met with enthusiasm from retailers.",
            "options": {"A": "introduce", "B": "introducing", "C": "introduction", "D": "introductory"},
            "correct_answer": "C",
            "explanation": "After 'the', a noun is needed. 'Introduction' is the noun form of 'introduce'.",
            "difficulty": "easy",
        },
        {
            "question_text": "Please ensure that all submitted reports are ______ formatted.",
            "options": {"A": "proper", "B": "properly", "C": "propriety", "D": "properties"},
            "correct_answer": "B",
            "explanation": "An adverb is needed to modify the past participle 'formatted'. 'Properly' = adjective 'proper' + -ly.",
            "difficulty": "easy",
        },
        {
            "question_text": "The merger created a ______ stronger company in a competitive market.",
            "options": {"A": "consider", "B": "considerable", "C": "considerately", "D": "considerably"},
            "correct_answer": "D",
            "explanation": "An adverb is needed to modify the adjective 'stronger'. 'Considerably' means 'by a large amount'.",
            "difficulty": "medium",
        },
        {
            "question_text": "Her ______ for detail makes her an excellent editor.",
            "options": {"A": "attentive", "B": "attend", "C": "attentively", "D": "attention"},
            "correct_answer": "D",
            "explanation": "After 'her' (possessive), a noun is needed. 'Attention for detail' is the standard phrase.",
            "difficulty": "medium",
        },
        {
            "question_text": "The ______ of the new office building took longer than expected.",
            "options": {"A": "construct", "B": "constructive", "C": "construction", "D": "constructively"},
            "correct_answer": "C",
            "explanation": "After 'the' (article), a noun is needed. 'Construction' is the noun form of 'construct'.",
            "difficulty": "easy",
        },
        {
            "question_text": "The proposal was rejected because it was not ______ feasible.",
            "options": {"A": "economy", "B": "economic", "C": "economically", "D": "economize"},
            "correct_answer": "C",
            "explanation": "An adverb is needed to modify the adjective 'feasible'. 'Economically' = adjective + -ly.",
            "difficulty": "medium",
        },
        {
            "question_text": "We need to ______ our product range to attract younger customers.",
            "options": {"A": "diversion", "B": "diversification", "C": "diverse", "D": "diversify"},
            "correct_answer": "D",
            "explanation": "After 'to' (infinitive marker), a base verb is needed. 'Diversify' = to make more diverse.",
            "difficulty": "medium",
        },
        {
            "question_text": "The survey revealed ______ high levels of job satisfaction among remote workers.",
            "options": {"A": "surprise", "B": "surprising", "C": "surprisingly", "D": "surprised"},
            "correct_answer": "C",
            "explanation": "An adverb is needed to modify the adjective 'high'. 'Surprisingly' intensifies the degree of 'high'.",
            "difficulty": "medium",
        },
        {
            "question_text": "The company is known for its ______ to environmental sustainability.",
            "options": {"A": "commit", "B": "committed", "C": "commitment", "D": "committing"},
            "correct_answer": "C",
            "explanation": "After 'its' (possessive), a noun is needed. 'Commitment' = the state of being committed.",
            "difficulty": "easy",
        },
        {
            "question_text": "The two departments operate ______, sharing resources and information regularly.",
            "options": {"A": "collaborate", "B": "collaboration", "C": "collaborative", "D": "collaboratively"},
            "correct_answer": "D",
            "explanation": "An adverb is needed to modify 'operate' (verb). 'Collaboratively' describes how they operate.",
            "difficulty": "medium",
        },
    ],
}


async def seed_question_bank():
    async with AsyncSessionLocal() as db:
        # Load topic slug → id mapping
        result = await db.execute(select(GrammarTopic))
        topics = {t.slug: t.id for t in result.scalars().all()}

        total_added = 0
        total_skipped = 0

        for slug, questions in QUESTIONS.items():
            topic_id = topics.get(slug)
            if not topic_id:
                print(f"  WARN: topic '{slug}' not found, skipping")
                continue

            # Clear existing bank questions for this topic (full refresh)
            await db.execute(
                delete(QuestionBank).where(QuestionBank.topic_id == topic_id)
            )

            for q in questions:
                db.add(QuestionBank(
                    topic_id=topic_id,
                    question_text=q["question_text"],
                    options=q["options"],
                    correct_answer=q["correct_answer"],
                    explanation=q["explanation"],
                    difficulty=q.get("difficulty", "medium"),
                ))
                total_added += 1

            print(f"  seeded {len(questions):2d} questions for: {slug}")

        await db.commit()
        print(f"\nDone. Added {total_added} questions to question bank.")


if __name__ == "__main__":
    asyncio.run(seed_question_bank())
